databaseType = "PostgreSql"
id = "7f3ce728-79f0-4571-87c1-8cf5d1ecb896"
name = "OMAv1"

[environments.development]
displayName = "Development database"
password = "madhan@123"
schemas = [ "public" ]
url = "jdbc:postgresql://localhost:5432/oma_sur_2"
user = "postgres"

[flyway]
callbackLocations = [ "filesystem:callbacks" ]
createSchemas = true
encoding = "UTF-8"
environment = "development"
locations = [ "filesystem:./db/migrations", "filesystem:./db/seeds" ]
mixed = true
outOfOrder = true
schemaModelLocation = "schema-model"
table = "flyway_schema_history"
validateMigrationNaming = false
validateOnMigrate = true

[flywayDesktop]
developmentEnvironment = "development"
shadowEnvironment = "shadow"
showDeploymentDecision = true

[redgateCompare]
filterFile = "filter.rgf"

[redgateCompare.postgresql.options.behavior]
detectRenames = "identical-only"

[redgateCompare.postgresql.options.ignores]
ignoreNewlinesInTextObjects = "off"